const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const root=path.resolve(__dirname,'..');const ctx={window:{}};const file=path.join(root,'src/assets/js/tokemoji-market.js');if(fs.existsSync(file))vm.runInNewContext(fs.readFileSync(file,'utf8'),ctx);const math=()=>{assert.ok(ctx.window.TokemojiPairMath,'pair calculation module exists');return ctx.window.TokemojiPairMath;};
test('General compares capitalizations, not prices',()=>assert.equal(math().general(300,100),75));
test('General missing or zero-total values are unavailable',()=>{for(const [a,b] of [[null,10],[undefined,20],[0,0],[-1,3],[Infinity,3]])assert.equal(math().general(a,b),null);assert.equal(math().general(0,10),0);});
test('24h uses relative growth factors and preserves signed pp spread',()=>{const v=math().day(20,-20);assert.equal(v.leftShare,60);assert.equal(v.spread,40);});
test('Two declines: smaller decline leads',()=>assert.ok(math().day(-10,-30).leftShare>50));
test('Equal daily returns produce balanced comparison',()=>assert.equal(math().day(12,12).leftShare,50));
test('Missing 24h and complete wipeout do not invent a balance',()=>{for(const [a,b] of [[null,0],[undefined,0],[-101,0],[-100,-100]])assert.equal(math().day(a,b),null);});
test('Sorting keeps missing quotes last in both directions',()=>{const rows=[{ticker:'X',changeRaw:null},{ticker:'A',changeRaw:-2},{ticker:'B',changeRaw:3}];assert.equal(math().sort(rows,'gainers').map(r=>r.ticker).join(','),'B,A,X');assert.equal(math().sort(rows,'losers').map(r=>r.ticker).join(','),'A,B,X');});
test('Original index is not hidden or replaced by the lab',()=>{const polish=fs.readFileSync(path.join(root,'src/assets/js/tokemoji-polish.js'),'utf8');assert.ok(!/body:has\(.tx-hero\) #barometer\{display:none/.test(polish));const layout=fs.readFileSync(path.join(root,'src/layouts/single-page.html'),'utf8');assert.ok(!layout.includes('tokemoji-sample-market.js'));assert.ok(!layout.includes('tokemoji-api-preview.js'));});
